# Generated by Django 4.1.7 on 2023-04-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
