# Generated by Django 4.1.7 on 2023-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepler', '0005_mensajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('pequeña_introduccion', models.CharField(max_length=1000)),
            ],
        ),
    ]
