# Generated by Django 4.1.7 on 2023-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepler', '0009_alter_posteo_descripcion_alter_posteo_encabezado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='texto_descriptivo',
            field=models.CharField(max_length=1000),
        ),
    ]
